// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmailAccountsByUser = `-- name: CountEmailAccountsByUser :one
SELECT COUNT(*) FROM email_accounts WHERE user_id = $1
`

func (q *Queries) CountEmailAccountsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEmailAccountsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmailAccount = `-- name: CreateEmailAccount :one
INSERT INTO email_accounts (user_id, email, imap_server, password_enc) VALUES ($1, $2, $3, $4) RETURNING id, user_id, email, imap_server, password_enc, is_active, last_connected, last_error, created_at, updated_at
`

type CreateEmailAccountParams struct {
	UserID      int64  `json:"user_id"`
	Email       string `json:"email"`
	ImapServer  string `json:"imap_server"`
	PasswordEnc []byte `json:"password_enc"`
}

func (q *Queries) CreateEmailAccount(ctx context.Context, arg CreateEmailAccountParams) (EmailAccount, error) {
	row := q.db.QueryRow(ctx, createEmailAccount,
		arg.UserID,
		arg.Email,
		arg.ImapServer,
		arg.PasswordEnc,
	)
	var i EmailAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.ImapServer,
		&i.PasswordEnc,
		&i.IsActive,
		&i.LastConnected,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateEmailAccount = `-- name: DeactivateEmailAccount :exec
UPDATE email_accounts SET is_active = FALSE WHERE id = $1 AND user_id = $2
`

type DeactivateEmailAccountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeactivateEmailAccount(ctx context.Context, arg DeactivateEmailAccountParams) error {
	_, err := q.db.Exec(ctx, deactivateEmailAccount, arg.ID, arg.UserID)
	return err
}

const deleteEmailAccount = `-- name: DeleteEmailAccount :exec
DELETE FROM email_accounts WHERE id = $1 AND user_id = $2
`

type DeleteEmailAccountParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteEmailAccount(ctx context.Context, arg DeleteEmailAccountParams) error {
	_, err := q.db.Exec(ctx, deleteEmailAccount, arg.ID, arg.UserID)
	return err
}

const getActiveEmailAccounts = `-- name: GetActiveEmailAccounts :many
SELECT id, user_id, email, imap_server, password_enc, is_active, last_connected, last_error, created_at, updated_at FROM email_accounts WHERE is_active = TRUE
`

func (q *Queries) GetActiveEmailAccounts(ctx context.Context) ([]EmailAccount, error) {
	rows, err := q.db.Query(ctx, getActiveEmailAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAccount{}
	for rows.Next() {
		var i EmailAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.ImapServer,
			&i.PasswordEnc,
			&i.IsActive,
			&i.LastConnected,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailAccountPassword = `-- name: GetEmailAccountPassword :one
SELECT password_enc FROM email_accounts WHERE id = $1
`

func (q *Queries) GetEmailAccountPassword(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRow(ctx, getEmailAccountPassword, id)
	var password_enc []byte
	err := row.Scan(&password_enc)
	return password_enc, err
}

const listEmailAccountsByUser = `-- name: ListEmailAccountsByUser :many
SELECT id, user_id, email, imap_server, is_active, last_connected, last_error, created_at FROM email_accounts WHERE user_id = $1 ORDER BY created_at
`

type ListEmailAccountsByUserRow struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Email         string             `json:"email"`
	ImapServer    string             `json:"imap_server"`
	IsActive      bool               `json:"is_active"`
	LastConnected pgtype.Timestamptz `json:"last_connected"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListEmailAccountsByUser(ctx context.Context, userID int64) ([]ListEmailAccountsByUserRow, error) {
	rows, err := q.db.Query(ctx, listEmailAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmailAccountsByUserRow{}
	for rows.Next() {
		var i ListEmailAccountsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Email,
			&i.ImapServer,
			&i.IsActive,
			&i.LastConnected,
			&i.LastError,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailAccountStatus = `-- name: UpdateEmailAccountStatus :exec
UPDATE email_accounts SET last_connected = $2, last_error = $3 WHERE id = $1
`

type UpdateEmailAccountStatusParams struct {
	ID            int64              `json:"id"`
	LastConnected pgtype.Timestamptz `json:"last_connected"`
	LastError     pgtype.Text        `json:"last_error"`
}

func (q *Queries) UpdateEmailAccountStatus(ctx context.Context, arg UpdateEmailAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateEmailAccountStatus, arg.ID, arg.LastConnected, arg.LastError)
	return err
}
