// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_codes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const codeExistsByBodyHash = `-- name: CodeExistsByBodyHash :one
SELECT EXISTS(SELECT 1 FROM email_codes WHERE raw_body_hash = $1) AS exists
`

func (q *Queries) CodeExistsByBodyHash(ctx context.Context, rawBodyHash pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, codeExistsByBodyHash, rawBodyHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createEmailCode = `-- name: CreateEmailCode :one
INSERT INTO email_codes (email_account_id, user_id, sender, subject, code, rule_name, raw_body_hash, tg_message_id, received_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, email_account_id, user_id, sender, subject, code, rule_name, raw_body_hash, tg_message_id, received_at, created_at
`

type CreateEmailCodeParams struct {
	EmailAccountID int64              `json:"email_account_id"`
	UserID         int64              `json:"user_id"`
	Sender         string             `json:"sender"`
	Subject        pgtype.Text        `json:"subject"`
	Code           string             `json:"code"`
	RuleName       pgtype.Text        `json:"rule_name"`
	RawBodyHash    pgtype.Text        `json:"raw_body_hash"`
	TgMessageID    pgtype.Int8        `json:"tg_message_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
}

func (q *Queries) CreateEmailCode(ctx context.Context, arg CreateEmailCodeParams) (EmailCode, error) {
	row := q.db.QueryRow(ctx, createEmailCode,
		arg.EmailAccountID,
		arg.UserID,
		arg.Sender,
		arg.Subject,
		arg.Code,
		arg.RuleName,
		arg.RawBodyHash,
		arg.TgMessageID,
		arg.ReceivedAt,
	)
	var i EmailCode
	err := row.Scan(
		&i.ID,
		&i.EmailAccountID,
		&i.UserID,
		&i.Sender,
		&i.Subject,
		&i.Code,
		&i.RuleName,
		&i.RawBodyHash,
		&i.TgMessageID,
		&i.ReceivedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldCodes = `-- name: DeleteOldCodes :execrows
DELETE FROM email_codes WHERE created_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) DeleteOldCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listRecentCodesByUser = `-- name: ListRecentCodesByUser :many
SELECT ec.id, ec.email_account_id, ec.user_id, ec.sender, ec.subject, ec.code, ec.rule_name, ec.raw_body_hash, ec.tg_message_id, ec.received_at, ec.created_at, ea.email FROM email_codes ec JOIN email_accounts ea ON ec.email_account_id = ea.id WHERE ec.user_id = $1 ORDER BY ec.received_at DESC LIMIT $2
`

type ListRecentCodesByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListRecentCodesByUserRow struct {
	ID             int64              `json:"id"`
	EmailAccountID int64              `json:"email_account_id"`
	UserID         int64              `json:"user_id"`
	Sender         string             `json:"sender"`
	Subject        pgtype.Text        `json:"subject"`
	Code           string             `json:"code"`
	RuleName       pgtype.Text        `json:"rule_name"`
	RawBodyHash    pgtype.Text        `json:"raw_body_hash"`
	TgMessageID    pgtype.Int8        `json:"tg_message_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Email          string             `json:"email"`
}

func (q *Queries) ListRecentCodesByUser(ctx context.Context, arg ListRecentCodesByUserParams) ([]ListRecentCodesByUserRow, error) {
	rows, err := q.db.Query(ctx, listRecentCodesByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentCodesByUserRow{}
	for rows.Next() {
		var i ListRecentCodesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.EmailAccountID,
			&i.UserID,
			&i.Sender,
			&i.Subject,
			&i.Code,
			&i.RuleName,
			&i.RawBodyHash,
			&i.TgMessageID,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
