// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExpenseType string

const (
	ExpenseTypeAgentki        ExpenseType = "agentki"
	ExpenseTypeAdpos          ExpenseType = "adpos"
	ExpenseTypeAntiqueService ExpenseType = "antique_service"
	ExpenseTypeOtherService   ExpenseType = "other_service"
	ExpenseTypeSetups         ExpenseType = "setups"
	ExpenseTypeProxy          ExpenseType = "proxy"
)

func (e *ExpenseType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseType(s)
	case string:
		*e = ExpenseType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseType: %T", src)
	}
	return nil
}

type NullExpenseType struct {
	ExpenseType ExpenseType `json:"expense_type"`
	Valid       bool        `json:"valid"` // Valid is true if ExpenseType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseType) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseType), nil
}

type PaymentMethod string

const (
	PaymentMethodUsdt PaymentMethod = "usdt"
	PaymentMethodTrx  PaymentMethod = "trx"
	PaymentMethodCard PaymentMethod = "card"
	PaymentMethodNone PaymentMethod = "none"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type RequestStatus string

const (
	RequestStatusPending   RequestStatus = "pending"
	RequestStatusApproved  RequestStatus = "approved"
	RequestStatusPaid      RequestStatus = "paid"
	RequestStatusRejected  RequestStatus = "rejected"
	RequestStatusCancelled RequestStatus = "cancelled"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type EmailAccount struct {
	ID            int64              `json:"id"`
	UserID        int64              `json:"user_id"`
	Email         string             `json:"email"`
	ImapServer    string             `json:"imap_server"`
	PasswordEnc   []byte             `json:"password_enc"`
	IsActive      bool               `json:"is_active"`
	LastConnected pgtype.Timestamptz `json:"last_connected"`
	LastError     pgtype.Text        `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type EmailCode struct {
	ID             int64              `json:"id"`
	EmailAccountID int64              `json:"email_account_id"`
	UserID         int64              `json:"user_id"`
	Sender         string             `json:"sender"`
	Subject        pgtype.Text        `json:"subject"`
	Code           string             `json:"code"`
	RuleName       pgtype.Text        `json:"rule_name"`
	RawBodyHash    pgtype.Text        `json:"raw_body_hash"`
	TgMessageID    pgtype.Int8        `json:"tg_message_id"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Request struct {
	ID             uuid.UUID          `json:"id"`
	UserID         int64              `json:"user_id"`
	ExpenseType    ExpenseType        `json:"expense_type"`
	PaymentMethod  NullPaymentMethod  `json:"payment_method"`
	Address        pgtype.Text        `json:"address"`
	AddressPhoto   pgtype.Text        `json:"address_photo"`
	Amount         pgtype.Numeric     `json:"amount"`
	AntiqueAccount pgtype.Text        `json:"antique_account"`
	Comment        string             `json:"comment"`
	Status         RequestStatus      `json:"status"`
	FlowType       string             `json:"flow_type"`
	TgMessageID    pgtype.Int8        `json:"tg_message_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Username  pgtype.Text        `json:"username"`
	FirstName string             `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	IsBlocked bool               `json:"is_blocked"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
