// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countRequestsByStatus = `-- name: CountRequestsByStatus :many
SELECT status, COUNT(*) as count FROM requests GROUP BY status
`

type CountRequestsByStatusRow struct {
	Status RequestStatus `json:"status"`
	Count  int64         `json:"count"`
}

func (q *Queries) CountRequestsByStatus(ctx context.Context) ([]CountRequestsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countRequestsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountRequestsByStatusRow{}
	for rows.Next() {
		var i CountRequestsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (user_id, expense_type, payment_method, address, address_photo, amount, antique_account, comment, flow_type, tg_message_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING id, user_id, expense_type, payment_method, address, address_photo, amount, antique_account, comment, status, flow_type, tg_message_id, created_at, updated_at
`

type CreateRequestParams struct {
	UserID         int64             `json:"user_id"`
	ExpenseType    ExpenseType       `json:"expense_type"`
	PaymentMethod  NullPaymentMethod `json:"payment_method"`
	Address        pgtype.Text       `json:"address"`
	AddressPhoto   pgtype.Text       `json:"address_photo"`
	Amount         pgtype.Numeric    `json:"amount"`
	AntiqueAccount pgtype.Text       `json:"antique_account"`
	Comment        string            `json:"comment"`
	FlowType       string            `json:"flow_type"`
	TgMessageID    pgtype.Int8       `json:"tg_message_id"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.UserID,
		arg.ExpenseType,
		arg.PaymentMethod,
		arg.Address,
		arg.AddressPhoto,
		arg.Amount,
		arg.AntiqueAccount,
		arg.Comment,
		arg.FlowType,
		arg.TgMessageID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpenseType,
		&i.PaymentMethod,
		&i.Address,
		&i.AddressPhoto,
		&i.Amount,
		&i.AntiqueAccount,
		&i.Comment,
		&i.Status,
		&i.FlowType,
		&i.TgMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, user_id, expense_type, payment_method, address, address_photo, amount, antique_account, comment, status, flow_type, tg_message_id, created_at, updated_at FROM requests WHERE id = $1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpenseType,
		&i.PaymentMethod,
		&i.Address,
		&i.AddressPhoto,
		&i.Amount,
		&i.AntiqueAccount,
		&i.Comment,
		&i.Status,
		&i.FlowType,
		&i.TgMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT r.id, r.user_id, r.expense_type, r.payment_method, r.address, r.address_photo, r.amount, r.antique_account, r.comment, r.status, r.flow_type, r.tg_message_id, r.created_at, r.updated_at, u.username, u.first_name FROM requests r JOIN users u ON r.user_id = u.id WHERE r.status = 'pending' ORDER BY r.created_at ASC
`

type ListPendingRequestsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         int64              `json:"user_id"`
	ExpenseType    ExpenseType        `json:"expense_type"`
	PaymentMethod  NullPaymentMethod  `json:"payment_method"`
	Address        pgtype.Text        `json:"address"`
	AddressPhoto   pgtype.Text        `json:"address_photo"`
	Amount         pgtype.Numeric     `json:"amount"`
	AntiqueAccount pgtype.Text        `json:"antique_account"`
	Comment        string             `json:"comment"`
	Status         RequestStatus      `json:"status"`
	FlowType       string             `json:"flow_type"`
	TgMessageID    pgtype.Int8        `json:"tg_message_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Username       pgtype.Text        `json:"username"`
	FirstName      string             `json:"first_name"`
}

func (q *Queries) ListPendingRequests(ctx context.Context) ([]ListPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingRequestsRow{}
	for rows.Next() {
		var i ListPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpenseType,
			&i.PaymentMethod,
			&i.Address,
			&i.AddressPhoto,
			&i.Amount,
			&i.AntiqueAccount,
			&i.Comment,
			&i.Status,
			&i.FlowType,
			&i.TgMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FirstName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUser = `-- name: ListRequestsByUser :many
SELECT id, user_id, expense_type, payment_method, address, address_photo, amount, antique_account, comment, status, flow_type, tg_message_id, created_at, updated_at FROM requests WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListRequestsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRequestsByUser(ctx context.Context, arg ListRequestsByUserParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpenseType,
			&i.PaymentMethod,
			&i.Address,
			&i.AddressPhoto,
			&i.Amount,
			&i.AntiqueAccount,
			&i.Comment,
			&i.Status,
			&i.FlowType,
			&i.TgMessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequestStatus = `-- name: UpdateRequestStatus :one
UPDATE requests SET status = $2 WHERE id = $1 RETURNING id, user_id, expense_type, payment_method, address, address_photo, amount, antique_account, comment, status, flow_type, tg_message_id, created_at, updated_at
`

type UpdateRequestStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status RequestStatus `json:"status"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequestStatus, arg.ID, arg.Status)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpenseType,
		&i.PaymentMethod,
		&i.Address,
		&i.AddressPhoto,
		&i.Amount,
		&i.AntiqueAccount,
		&i.Comment,
		&i.Status,
		&i.FlowType,
		&i.TgMessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
