// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, first_name, last_name, is_blocked, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isUserBlocked = `-- name: IsUserBlocked :one
SELECT is_blocked FROM users WHERE id = $1
`

func (q *Queries) IsUserBlocked(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBlocked, id)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, username, first_name, last_name) VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET username = EXCLUDED.username, first_name = EXCLUDED.first_name, last_name = EXCLUDED.last_name RETURNING id, username, first_name, last_name, is_blocked, created_at, updated_at
`

type UpsertUserParams struct {
	ID        int64       `json:"id"`
	Username  pgtype.Text `json:"username"`
	FirstName string      `json:"first_name"`
	LastName  pgtype.Text `json:"last_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Username,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FirstName,
		&i.LastName,
		&i.IsBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
